"use client";

import React from "react";
import "./admin.css";

const AdminLandingPage = () => {
  return (
    <div className="ad-land-container">
      <header className="ad-land-header">
        <h1 className="ad-land-heading">Welcome, Admin! 👩‍💼👨‍💼</h1>
        <p className="ad-land-subtitle">Manage everything with ease 🚀</p>
      </header>

      <main className="ad-land-main">
        <section className="ad-land-dashboard">
          <h2 className="ad-land-section-heading">Quick Links 🔗</h2>
          <div className="ad-land-link-grid">
            <div className="ad-land-link-card">
              <h3>📋 View Reports</h3>
              <p>Analyze and export detailed reports.</p>
            </div>
            <div className="ad-land-link-card">
              <h3>👥 Manage Users</h3>
              <p>Add, remove, or update user roles.</p>
            </div>
            <div className="ad-land-link-card">
              <h3>📢 Announcements</h3>
              <p>Post important updates for all members.</p>
            </div>
            <div className="ad-land-link-card">
              <h3>⚙️ Settings</h3>
              <p>Customize the system configurations.</p>
            </div>
          </div>
        </section>

        <section className="ad-land-analytics">
          <h2 className="ad-land-section-heading">Analytics 📊</h2>
          <p className="ad-land-analytics-text">
            Get insights into system performance, user activity, and more.
          </p>
          <div className="ad-land-analytics-summary">
            <div className="ad-land-analytics-card">
              <h3>👥 Total Users</h3>
              <p>1,245</p>
            </div>
            <div className="ad-land-analytics-card">
              <h3>📝 Total Posts</h3>
              <p>532</p>
            </div>
            <div className="ad-land-analytics-card">
              <h3>📈 Monthly Active Users</h3>
              <p>860</p>
            </div>
          </div>
        </section>

        <section className="ad-land-updates">
          <h2 className="ad-land-section-heading">Recent Activities 🕒</h2>
          <ul className="ad-land-updates-list">
            <li>📋 Report generated by Admin A on Jan 25</li>
            <li>👤 New user registered: Teacher B</li>
            <li>📢 Announcement posted: Meeting on Feb 1</li>
            <li>⚙️ Settings updated by Admin C</li>
          </ul>
        </section>
      </main>
    </div>
  );
};

export default AdminLandingPage;
